### ISSUE TITLE
New types of SNV data at GDC: needs scrutiny

### ISSUE THREAD

**Issue by noblem** [broadinstitute/gdctools#45]
The GDC now distinguishes between "raw" and "annotated" mutation data in the corpus of data it serves, and we need to make sure that we're **(A)** processing all of them properly and **(B)** choosing the best ones to funnel downstream for analyses.

![screen shot 2017-06-21 at 12 34 51 pm](https://user-images.githubusercontent.com/3883143/27395532-1dd35876-567e-11e7-8305-641896c4b41b.png)

**Comment by dheiman** [comment]
This is not new, they've simply changed the names. Annotated simply means
they've been processed with VEP, a necessary step before generating MAFs.
Look closely at the file counts, and you'll see that those are the sample
level VCFs, not MAFs.

On Jun 21, 2017 12:37 PM, "noblem" <notifications@github.com> wrote:

Assigned #45 <https://github.com/broadinstitute/gdctools/issues/45> to
@dheiman <https://github.com/dheiman>.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/broadinstitute/gdctools/issues/45#event-1133267954>,
or mute
the thread

**Comment by noblem** [comment]
Hmm, why are you answering emails on vacation?   Anyway ... OK, so (A) and (B) are effectively already being met, nice.
